### ISSUE TITLE
Apple Silicon Macs?

### ISSUE THREAD

**Issue by ArguingMeadows** [imxieyi/waifu2x-ios#18]
With the Apple Silicon Macs coming up will you merge the MacOS and iOS versions into one central app or will they continue on seperately?

**Comment by imxieyi** [comment]
AFAIK the limitations on iOS still apply to iOS apps on Apple Silicon Macs. Some features like free-form windows and command line support won't be possible with such version. So that the two versions will be kept separately in foreseeable future.

**Comment by imxieyi** [comment]
It turns out that free-form windows is already working under ARM Mac. However CLI won't work. Running binary directly will result in `EXEC, [0xe] Binary with wrong platform` error. iOS apps are wrapped by a macOS native bundle, which does not support CLI. There is no reason to merge two versions because of such platform differences.
