### ISSUE TITLE
[Bug/annoyance] Drag and drop area is too small and obstructed by text

### ISSUE THREAD

**Issue by morning-paradigm** [imxieyi/waifu2x-ios#31]
The title says it all. You have to aim into a specific area, otherwise it won't work and you'll need to drag and drop again.

https://user-images.githubusercontent.com/39773982/127864858-196a17cb-705f-468b-9801-6de4695e4d8a.mp4

**Comment by imxieyi** [comment]
This is due to limitations of SwiftUI where you cannot passthrough UI events to views below if it's not a drop event. Making the drop area larger will result in interface covered by the drop area not responding to other input (scroll, click, etc.). Probably this can be worked around now with [Introspect](https://github.com/siteline/SwiftUI-Introspect).

**Comment by imxieyi** [comment]
This issue is now resolved in the new "waifu2x" app for macOS. Feel free to update.
