### ISSUE TITLE
[feature] export as gif or mp4

### ISSUE THREAD

**Issue by sayomelu** [imxieyi/waifu2x-ios#35]
now waifu2x can import gif, but can only export static image format. if waifu2x can import animated gif and export it in high res, it would be much better. (also for some animated video format)

considering about the ram usage, using [anime4k](https://github.com/bloc97/Anime4K) may be a good idea.

**Comment by imxieyi** [comment]
It's not worth preprocess a video using Anime4K. It's very lightweight and can even scale 1080p->4k in real time on the old Apple TV 4K (A10X). See [Anime4K-tvOS](https://github.com/imxieyi/Anime4K-tvOS) if you are interested.

GIF support is already planned for a future release.

Video support will be available once the updated macOS version is released, which will be only available to the macOS version for the following reasons:
- Videos can easily contain 10000+ frames, which will take forever on a mobile device.
- iOS and macOS built-in video encoder and decoder are extremely limited. For example, YUV444 is not supported at all. For the best experience an external encoder and decoder is required, in most case ffmpeg. Due to license issues in most video libraries including libx264 and libx265 the external encoder and decoder cannot be shipped with this app.

**Comment by sayomelu** [comment]
as a recent anime4k example, the result of anime4k is even better than waifu2x. ![](https://github.com/bloc97/Anime4K/raw/master/results/Comparisons/Cropped_Screenshots/Magia_360p_4K.png)

**Comment by imxieyi** [comment]
GIF and video support is now available on the latest version (5.2.0). Feel free to update.
