### ISSUE TITLE
Reduce memory usage

### ISSUE THREAD

**Issue by soywiz** [imxieyi/waifu2x-ios#4]
Thanks for the iOS version. Works like a charm!

I did an opencl port sometime ago. And I faced the same problem of high memory usage. I solved it by slicing the image in several 128x128 chunks:
https://github.com/soywiz/kaifu2x#some-numbers-v030

The idea is:

Add a transparent padding 7 pixels at the left, 7 top, 7 right, 7 bottom to the original 2x nearest neighbour image. Then you get a 128x128 chunk (for example):

The first chunk to process would be (x=7,y=7,width=128,height=128).
Then from the resulting image, you get just width=114,height=114 and place in the final image at x=0,y=0.
For the next chunk you would use x=7+114,y=7,width=128,height=128, and place at x=114,y=0.
(The width/height can be 128 or less if the image with edges is not multiple of 128.)

You are processing more pixeles like this (you can reduce the additional processing by increasing the chunk size, though 128x128 is usually a good chunk size), but you won't get artifacts and will reduce the memory requirements and will be able to process even larger images on the gpu.

Processing the full image 1500x1500 would produce an image 3000x3000, and would require 3000x3000x4x256 bytes (a lot of memory). While in chunks it would be 128x128x4x256 = 16MB in the GPU. Or 256x256 chunks: 256x256x4x256 = 64MB

You can do the same trick for the bicubic interpolation. Also you can apply waifu2x per component instead of RGB and apply the waifu2x to the alpha channel too.

**Comment by imxieyi** [comment]
Thanks for your advice!
Currently Core ML does not support input arrays of any size. So actually images are sliced into `142x142` chunks to process. However, a lot of memory is still required to store both input and output images. For a `3000x3000` image scaled to 2x, it needs `3000x3000x4x4=140M` for input (stored in float32) and `6000x6000x4=140M` for output (stored in uint8).
To save additional memory, maybe input image could also be stored in uint8. But the problem is that on iOS images are stored in premultiplied alpha. Before processing it should be recovered to original RGB, which cannot be done with only uint8 format. In this implementation the input image is stored in float32 to solve this issue and reduce overhead from format converting.
Actually even on an iPhone 5s with only 1GB RAM, it can handle a `3000x3000` RGBA image scaled to 2x (in theory, not tested). However, in practice I have received many crash reports because of lacking memory. For example, one of them scales a `7500x4000` image to 4x on a device with 2GB RAM. In this situation the image alone takes up 950M memory, not including other application overhead and processing needs.

**Comment by soywiz** [comment]
I see :) didn’t check the implementation and thought it was related to not being partitioned in chunks.

Also didnt know that when I download a png image for example from dropbox to the camera roll, it premultiplies it. Thats a pity.

I will check the implementation when I have some time.

Again, thanks for your work. It works just fine! :)
