### ISSUE TITLE
Problems with gpu calls in normal mode

### ISSUE THREAD

**Issue by ybaybaybaybayba** [imxieyi/waifu2x-ios#75]
There are almost no gpu calls visible under the mac activity monitor, and the overall speed is slow.
![WeChat0810295ed2937dc14b6998844dcd8af8](https://github.com/user-attachments/assets/8aa0d705-08cb-4af4-9775-7c3439725399)

**Comment by imxieyi** [comment]
Are you using Apple Silicon Mac? If so please check `ANE Usage` using [asitop](https://github.com/tlkh/asitop).

**Comment by ybaybaybaybayba** [comment]
<img width="697" alt="image" src="https://github.com/user-attachments/assets/97d44993-8e70-45b4-9455-37c4e6d9858b">
<img width="809" alt="image" src="https://github.com/user-attachments/assets/8ecd9d7a-6945-466a-9602-9e3ada8a50e3">
I used asitop, but it still doesn't seem to be calling much gpu at work, and the activity monitor still does the same.

**Comment by imxieyi** [comment]
Please pay attention to ANE usage. It's the Neural Engine, which is dedicated to running neural networks and way faster than GPU.

**Comment by ybaybaybaybayba** [comment]
I see, sorry I didn't notice that.
 Can you please add the ability to use cpu+gpu+npu at the same time, like draw things.

**Comment by imxieyi** [comment]
Looks like the "All" option for Core ML in draw things is referring to `all` in [MLComputeUnits](https://developer.apple.com/documentation/coreml/mlcomputeunits). This app is already using this option.

In your case the Core ML framework decides to use only ANE to run the model, which is likely the fastest way. And as you can see the ANE usage is even higher than 100%. I tried Draw Things and its ANE usage was way lower than 100%.

It's slow just because videos must be processed frame by frame. 1 second of video is usually equivalent to 24 images of the same resolution.

That being said, if you are processing at least 2 videos, you can enable Parallel Processing option in this app to force using GPU to process another video at the same time:

![image](https://github.com/user-attachments/assets/8d2068eb-1879-4446-85c0-28a0072e2355)

**Comment by ybaybaybaybayba** [comment]
Thank you for your careful answer. I'm sorry I didn't find the interface in the picture you provided, can you tell me where it is in the program?

**Comment by imxieyi** [comment]
In the interface where you configure which model to use, on the top left side click "Basic" and change it to "Advanced":

![image](https://github.com/user-attachments/assets/1c9b3d17-5b20-4ca5-a783-5eb1b2bb5699)

Then you can scroll to the bottom and find the Parallel Processing option.

**Comment by ybaybaybaybayba** [comment]
I see, it's a shame that after using the software for so long this is the first time I've known about this feature, thank you for your answer!
